version: "2.1"

services:
  coding-coach-api:
    build: .
    command: npm run start
    volumes:
      - ./:/home/node/app
      # - /home/node/node_modules
    working_dir: /home/node/app
    ports:
      - '7071:7071'
  coding-coach-azurite:
    build: .
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    expose:
      - 10000
      - 10001
      - 10002